version: '3.7'

services:

  api:
    container_name: 'itam-dima-back'
    image: 'itam-dima-back'
    build:
      context: .
      dockerfile: Backend.Dockerfile
    ports:
      - "5000:80"
      - "5000:443"
    depends_on:
      - "postgres"
    networks:
      - itam-dima-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      # change this for a "real" app!
      POSTGRES_PASSWORD: password
    networks:
      - itam-dima-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  itam-dima-network:
    driver: bridge
    
volumes:
  pgdata: