version: '3.7'

services:

  api:
    container_name: 'itam-dima-back'
    image: 'itam-dima-back'
    build:
      dockerfile: Backend.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Postgres: "User ID=postgres;Password=itampassword123;Host=postgres;Port=5432;"
    ports:
      - "5080:80"
    depends_on:
      - "postgres"
      - "minio"
    networks:
      - itam-dima-network
        
  fornt:
    build: 
      context: ./front
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: 'itam-dima-back:5080'
    ports:
      - "80:80"
    container_name: front
    
  bot:
    build:
      context: ./tg-bot
      dockerfile: Dockerfile
    environment:
      API_BASE_URL: 'itam-dima-back:80'
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    networks:
      - itam-dima-network

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "itampassword123"
    networks:
      - itam-dima-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: itam-dima
      MINIO_ROOT_PASSWORD: itam-dima123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - itam-dima-network

networks:
  itam-dima-network:
    driver: bridge  
    
volumes:
  pgdata:
  minio-storage: